// DeviceFactory.js – Refactored with Azitrend model support
const path = require('path');
const fs = require('fs');
const net = require('net');

const HikvisionAdapter = require('./HikvisionAdapter');
const DahuaAdapter = require('./DahuaAdapter');
const BaseAdapter = require('./BaseAdapter');
const GenericAdapter = require('./GenericAdapter');

// Load Azitrend models database (generated by scan_azitrend_all.ps1)
let azitrendModels = {};
try {
    const modelsPath = path.join(__dirname, '../../local-api/models.json');
    if (fs.existsSync(modelsPath)) {
        let raw = fs.readFileSync(modelsPath, 'utf8');
        // Remove UTF-8 BOM if present
        raw = raw.replace(/^\uFEFF/, '');
        azitrendModels = JSON.parse(raw);
        console.log('[DeviceFactory] Loaded Azitrend models.json');
    }
} catch (e) {
    console.warn('[DeviceFactory] Failed to load models.json:', e.message);
}

class DeviceFactory {
    /** Check if a TCP port is open */
    static checkTcpPort(host, port, timeout = 1500) {
        return new Promise(resolve => {
            const socket = new net.Socket();
            socket.setTimeout(timeout);
            socket.on('connect', () => { socket.destroy(); resolve(true); });
            socket.on('timeout', () => { socket.destroy(); resolve(false); });
            socket.on('error', () => { socket.destroy(); resolve(false); });
            socket.connect(port, host);
        });
    }

    /** Ultra‑fast smart probe that tries several strategies */
    static async smartProbe(config) {
        // Ensure we have a numeric port (default 80) for later logic
        config.port = config.port || 80;

        // Log start
        try { fs.appendFileSync('/tmp/dss_debug.log', `[${new Date().toISOString()}] SMARTPROBE START: ${config.ip}\n`); } catch (e) { }
        console.log(`[DeviceFactory] SmartProbe starting for ${config.ip}...`);

        // Fast‑path for explicit Trassir (case‑insensitive)
        if ((config.manufacturer || '').toLowerCase() === 'trassir') {
            console.log(`[DeviceFactory] Manual 'Trassir' selection. Applying Trassir RTSP library.`);
            const safeUser = encodeURIComponent(config.user);
            const safePass = encodeURIComponent(config.pass);
            const trassirStreams = {
                main: `rtsp://${safeUser}:${safePass}@${config.ip}:554/live/main`,
                sub: `rtsp://${safeUser}:${safePass}@${config.ip}:554/live/sub`
            };
            const trassirConfig = { ...config, manufacturer: 'Trassir', streams: trassirStreams };
            const adapter = new GenericAdapter(trassirConfig);
            adapter.config.rtspHd = trassirStreams.main;
            adapter.config.rtsp = trassirStreams.sub;
            return { adapter, config: trassirConfig };
        }

        // ------------------------------------------------------------
        // Scan common ports in parallel
        const portTests = [
            { port: 80, name: 'HTTP/ONVIF' },
            { port: 554, name: 'RTSP' },
            { port: 37777, name: 'Dahua SDK' },
            { port: 8000, name: 'Hikvision SDK' }
        ];
        const openPorts = {};
        await Promise.all(portTests.map(async t => {
            openPorts[t.port] = await DeviceFactory.checkTcpPort(config.ip, t.port);
        }));
        console.log(`[DeviceFactory] Open ports for ${config.ip}:`, Object.keys(openPorts).filter(p => openPorts[p]).join(', '));

        // ------------------------------------------------------------
        // Strategy 1 – Known manufacturers (Dahua / Hikvision)
        if (openPorts[37777]) {
            console.log(`[DeviceFactory] Dahua signature detected on 37777. SDK Missing - Skipping explicit DahuaAdapter.`);
            // Skip SDK usage
        }

        if (openPorts[8000]) {
            console.log(`[DeviceFactory] Hikvision signature detected on 8000. Using HikvisionAdapter.`);
            const hikConfig = { ...config, manufacturer: 'Hikvision', port: 80 };
            const adapter = new HikvisionAdapter(hikConfig);
            if (await adapter.connect()) {
                const info = await adapter.getDeviceInfo();
                Object.assign(adapter.config, info);
                return { adapter, config: { ...hikConfig, ...info } };
            }
        }

        // ------------------------------------------------------------
        // Strategy 2 – Azitrend model database inference
        if (config.model && azitrendModels.manufacturers) {
            const modelUpper = config.model.toUpperCase();
            for (const mfg of azitrendModels.manufacturers) {
                if (mfg.models && mfg.models.some(m => m.toUpperCase() === modelUpper)) {
                    console.log(`[DeviceFactory] Model '${config.model}' matched Azitrend manufacturer '${mfg.name}'.`);
                    const safeUser = encodeURIComponent(config.user);
                    const safePass = encodeURIComponent(config.pass);
                    let rtspMain = '';
                    let rtspSub = '';
                    const manuf = mfg.name.toLowerCase();
                    if (manuf.includes('dahua')) {
                        rtspMain = `rtsp://${safeUser}:${safePass}@${config.ip}:554/cam/realmonitor?channel=1&subtype=0`;
                        rtspSub = `rtsp://${safeUser}:${safePass}@${config.ip}:554/cam/realmonitor?channel=1&subtype=1`;
                    } else if (manuf.includes('hikvision')) {
                        rtspMain = `rtsp://${safeUser}:${safePass}@${config.ip}:554/Streaming/Channels/101`;
                        rtspSub = `rtsp://${safeUser}:${safePass}@${config.ip}:554/Streaming/Channels/102`;
                    } else if (manuf.includes('trassir')) {
                        rtspMain = `rtsp://${safeUser}:${safePass}@${config.ip}:554/live/main`;
                        rtspSub = `rtsp://${safeUser}:${safePass}@${config.ip}:554/live/sub`;
                    } else {
                        // Generic fallback
                        rtspMain = `rtsp://${safeUser}:${safePass}@${config.ip}:554/stream1`;
                        rtspSub = `rtsp://${safeUser}:${safePass}@${config.ip}:554/stream2`;
                    }
                    const inferredConfig = { ...config, manufacturer: mfg.name, streams: { main: rtspMain, sub: rtspSub } };
                    const genericAdapter = new GenericAdapter(inferredConfig);
                    genericAdapter.config.rtspHd = rtspMain;
                    genericAdapter.config.rtsp = rtspSub;
                    return { adapter: genericAdapter, config: inferredConfig };
                }
            }
        }

        // ------------------------------------------------------------
        // Strategy 3 – ONVIF generic discovery (port 80)
        if (openPorts[80]) {
            console.log(`[DeviceFactory] Port 80 open, trying ONVIF discovery.`);
            const onvifConfig = { ...config, port: 80 };
            if (!onvifConfig.manufacturer) onvifConfig.manufacturer = 'Generic / ONVIF';
            const adapter = new GenericAdapter(onvifConfig);
            if (await adapter.connect()) {
                const info = await adapter.getDeviceInfo();
                Object.assign(adapter.config, info);
                return { adapter, config: { ...onvifConfig, ...info } };
            }
        }

        // ------------------------------------------------------------
        // Strategy 4 – Raw RTSP fallback (port 554)
        if (openPorts[554]) {
            console.log(`[DeviceFactory] RTSP port 554 open. Using Generic RTSP fallback.`);
            const rtspConfig = { ...config, manufacturer: 'Generic RTSP', port: 554 };
            const adapter = new GenericAdapter(rtspConfig);
            const info = await adapter.getDeviceInfo();
            Object.assign(adapter.config, info);
            return { adapter, config: { ...rtspConfig, ...info } };
        }

        console.log('[DeviceFactory] All strategies failed.');
        return null;
    }

    /** Create adapter based on sanitized config */
    static createAdapter(cameraConfig) {
        const cleanConfig = { ...cameraConfig };
        ['ip', 'user', 'pass'].forEach(key => {
            if (typeof cleanConfig[key] === 'string') {
                cleanConfig[key] = cleanConfig[key].replace(/\\/g, '');
            }
        });
        const manuf = (cleanConfig.manufacturer || '').toLowerCase();
        switch (manuf) {
            case 'hikvision':
                return new HikvisionAdapter(cleanConfig);
            case 'dahua':
                // SDK Missing fallback
                console.warn(`[DeviceFactory] Dahua SDK missing. Fallback to GenericAdapter for ${cleanConfig.ip}`);
                // Ensure streams are constructed if missing?
                if (!cleanConfig.rtsp) {
                    const safeUser = encodeURIComponent(cleanConfig.user);
                    const safePass = encodeURIComponent(cleanConfig.pass);
                    cleanConfig.rtsp = `rtsp://${safeUser}:${safePass}@${cleanConfig.ip}:554/cam/realmonitor?channel=1&subtype=1`;
                    cleanConfig.rtspHd = `rtsp://${safeUser}:${safePass}@${cleanConfig.ip}:554/cam/realmonitor?channel=1&subtype=0`;
                }
                return new GenericAdapter(cleanConfig);
            default:
                return new GenericAdapter(cleanConfig);
        }
    }

    /** Placeholder validation – always true for now */
    static validateStream(rtspUrl) { return Promise.resolve(true); }
}

module.exports = DeviceFactory;
